# Generated by Django 4.0.1 on 2022-02-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='coutry',
            new_name='country',
        ),
    ]
